#!/bin/sh
cd ${0%/*}
node _ASSETS/tool/typedoc/bin/typedoc --includeDeclarations lib/ts --externalPattern **/lib/** --mode file --name "HTML5 TypeScript Game Engine Primer Documentation" --out doc/ src/
